import Head from 'next/head';
import Layout from '@/components/layout';
import HeroSection from '@/components/landing/hero-section';
import ExploreSection from '@/components/landing/explore-section';
import FaqsSection from '@/components/landing/faqs-section';
import DiscoverSection from '@/components/landing/discover-section';
import { Inter } from '@next/font/google';
import ServiceSection from '@/components/landing/service-section';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Sampit Sport ID</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <ExploreSection />
      <FaqsSection />
      <DiscoverSection />
      <ServiceSection />
    </Layout>
  );
}
